[package]
name = "heim"
version = "0.0.4"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform framework for system information"
keywords = ["heim", "system", "information", "sysinfo", "psutil"]
categories = ["asynchronous", "os", "api-bindings"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
heim-common = { version = "0.0.4", path = "../heim-common" }
heim-derive = { version = "0.0.4", path = "../heim-derive" }
heim-cpu = {version = "0.0.4", path = "../heim-cpu", optional = true }
heim-disk = {version = "0.0.4", path = "../heim-disk", optional = true }
heim-host = { version = "0.0.4", path = "../heim-host", optional = true }
heim-memory = {version = "0.0.4", path = "../heim-memory", optional = true }
heim-net = {version = "0.0.4", path = "../heim-net", optional = true }
heim-process = { version = "0.0.4", path = "../heim-process", optional = true }
heim-virt = { version = "0.0.4", path = "../heim-virt", optional = true }

[features]
default = ["host", "cpu", "memory", "disk", "net", "process", "virt"]
host = ["heim-host"]
cpu = ["heim-cpu"]
memory = ["heim-memory"]
disk = ["heim-disk"]
net = ["heim-net"]
process = ["heim-process"]
virt = ["heim-virt"]
doc = [
    "heim-common/doc",
    "heim-host/doc",
    "heim-cpu/doc",
    "heim-memory/doc",
    "heim-disk/doc",
    "heim-net/doc",
    "heim-process/doc",
    "heim-virt/doc",
]

[package.metadata.docs.rs]
features = ["doc"]
