[package]
name = "heim-process"
version = "0.0.2"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform processes information"
keywords = ["heim", "system", "process", "information"]
categories = ["asynchronous", "os"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
heim-derive = { version = "0.0.2", path = "../heim-derive" }
heim-common = { version = "0.0.2", path = "../heim-common" }
cfg-if = "0.1.7"
libc = "^0.2"

[dev-dependencies]
runtime = "0.3.0-alpha.6"

[features]
doc = []

[package.metadata.docs.rs]
features = ["doc"]
