parameters:
    toolchain: ''

jobs:
    - job: ${{ parameters.name }}
      pool:
          vmImage: ${{ parameters.vmImage }}

      steps:
          - template: install-rust.yml
            parameters:
                toolchain: ${{ parameters.toolchain }}

          - script: |
                cargo +${{ parameters.toolchain }} build --all --all-features
            displayName: Build sources

          - script: |
                cargo +${{ parameters.toolchain }} test --all --all-features
            condition: eq('${{ parameters.toolchain }}', 'nightly')
            displayName: Run tests (nightly only)
