[package]
name = "heim-runtime"
version = "0.0.1"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Blocking tokio runtime optionally used by heim crate"
keywords = ["heim", "system", "information", "runtime"]
categories = ["asynchronous", "os"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
heim-common = { version = "0.0.1", path = "../heim-common" }
futures = "0.1.25"

[dependencies.tokio]
version = "0.1.18"
default-features = false
features = ["rt-full", "sync"]

[package.metadata.docs.rs]
features = ["doc"]
